name: Build and Deploy to cPanel
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.8.1

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to cPanel
        run: |
          git add .
          git commit -m "Build for deployment"
          git push