name: Deploy to cPanel

on:
 push:
  branches:
    - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Setup Node.js environment
    uses: actions/setup-node@v2
    with:
      node-version: '18'

  - name: Install dependencies and build
    run: |
      cd client
      npm install
      npm run build

  - name: Deploy to cPanel
    uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    with:
      server: ${{ secrets.FTP_SERVER }}
      username: ${{ secrets.FTP_USERNAME }}
      password: ${{ secrets.FTP_PASSWORD }}
      local-dir: ./client/dist
      server-dir: /github.shubhamlal.in/
      exclude: |
        **/.git
        **/.git*/**
        **/node_modules/**
        **/.**