name: Deploy to cPanel

on:
 push:
  branches:
    - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Setup Node.js environment
    uses: actions/setup-node@v2
    with:
      node-version: '18'

  - name: Install dependencies and build
    run: |
      cd client
      npm install
      npm run build

  - name: Install lftp
    run: sudo apt install lftp

  - name: Configure lftp
    run: |
      mkdir ~/.lftp
      echo "set ssl:verify-certificate false;" >> ~/.lftp/rc

  - name: Load Secrets
    run: |
      echo "machine ${{ secrets.FTP_SERVER }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc

  - name: Upload dist folder
    run: |
      lftp -e "mirror --only-newer --parallel=100 -R ./client/dist /github.shubhamlal.in/" ${{ secrets.FTP_SERVER }}